const API_BASE_URL = 'http://localhost:5000';
const NANOSECONDS_PY = 1;
const MICROSECONDS_PY = 1000 * NANOSECONDS_PY;
const MILLISECONDS_PY = 1000 * MICROSECONDS_PY;

export { API_BASE_URL, MILLISECONDS_PY };
